services:
  - type: web
    name: digichain-employee-api
    env: node
    rootDir: server
    buildCommand: npm install && npx prisma generate
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: CLIENT_URL_REGEX
        sync: false
      - key: CLOUDINARY_URL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
